services:
  localdb:
    container_name: projectdb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: indicampdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
    volumes:
      - ./mysql:/var/lib/mysql
